# Generated by Django 2.0.1 on 2018-01-19 12:57

from django.db import migrations, models
import django.db.models.deletion
import quote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('name_company', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('tel_office', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('tel_mobile', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('tel_fax', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('type_product', models.CharField(max_length=60)),
                ('direction', models.CharField(max_length=110)),
                ('detail', models.TextField()),
                ('file_path', models.FileField(blank=True, null=True, upload_to=quote.models.upload_image_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=30)),
                ('detail_type', models.CharField(default='no description here.', max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='type_quote',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quote.TypeQuote'),
        ),
    ]
