# Generated by Django 2.0.1 on 2018-01-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typequote',
            name='name_type',
        ),
        migrations.AddField(
            model_name='typequote',
            name='name_type_cn',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typequote',
            name='name_type_en',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typequote',
            name='name_type_th',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
